CHANGELOG.md
README.md
src/CosmosDB.psm1
src/lib/collections.ps1
test/CosmosDB.collections.Tests.ps1
test/CosmosDB.integration.Tests.ps1

Fix creation of spatial index by `New-CosmosDbCollectionIncludedPathIndex` so that precision is not used when passing to `New-CosmosDbCollection`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/118)

Fix creation of spatial index - Fixes #115

---

CHANGELOG.md
src/lib/storedprocedures.ps1
test/CosmosDB.storedprocedures.Tests.ps1

- Added support for `-PartitionKey` in `Invoke-CosmosDbStoredProcedure` - See [Issue #116](https://github.com/PlagueHO/CosmosDB/issues/116)
- Changed -StoredProcedureParameter from string[] to object[] - See [Issue #116](https://github.com/PlagueHO/CosmosDB/issues/116)
- Updated `Invoke-CosmosDbStoredProcedure` to set `x-ms-documentdb-script-enable-logging: true` header and write stored procedure logs to the Verbose Stream when `-Debug` is set - See [Issue #116](https://github.com/PlagueHO/CosmosDB/issues/116)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/117)

Enhance Invoke-CosmosDbStoredProcedure - Issue #116

---

CHANGELOG.md
README.md
RELEASENOTES.md
docs/New-CosmosDbBackoffPolicy.md
docs/New-CosmosDbContext.md
src/CosmosDB.psd1
src/CosmosDB.psm1
src/en-US/CosmosDB.strings.psd1
src/lib/utils.ps1
test/CosmosDB.utils.Tests.ps1

This PR adds support for supplying a Back-off Policy within the context so that all functions can be configured to handle 429 responses from the server. The Back-off Policy is configurable to support additional performance profiles and scenarios.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/127)

Add Support for Back-off Policy to handle 429 - Fixes #87

---

CHANGELOG.md
src/lib/storedprocedures.ps1
src/lib/utils.ps1
test/CosmosDB.utils.Tests.ps1

- Changed `New-CosmosDbStoredProcedure` & `Set-CosmosDbStoredProcedure` commandlets to use serialization instead of tricky request body conversion.
- Extracted request body serialization function `Convert-CosmosDbRequestBody` for that. That function can also be used in other places where request body is built.
- Added simple unit tests for `Convert-CosmosDbRequestBody` function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/138)

Changed New-CosmosDbStoredProcedure & Set-CosmosDbStoredProcedure commandlets to use serialization. Fixes #137.

---

CHANGELOG.md
src/lib/collections.ps1

- Fixes #153
- N/A
@PlagueHO Here's the fix for that trivial partition key issue I opened last week
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/154)

Trim leading slashes off of partition key value in lib\collections.ps1. Fixes: #153

---

CHANGELOG.md
src/lib/storedprocedures.ps1
src/lib/utils.ps1

Use the pound / hash sign to indicate which GitHub issues this Pull Request fixes, if applicable.
- RU Display (Issue #168)
- Stored procedure debug logging
- Retry logic not working
@PlagueHO
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/180)

Resolve Powershell CORE Issues

---

CHANGELOG.md
appveyor.yml
azure-pipelines.yml
build.ps1
cosmosdb.depend.psd1
psakefile.ps1
src/CosmosDB.psd1

This PR refactors the PSake file to be able to perform deployment in Azure DevOps.
- Fixes #179 
- Rework CI process to simplify code.
- Enabled integration test execution in Azure DevOps Pipelines - fixes Issue #179
- Added artifact publish tasks for Azure Pipeline.
- Refactored module deployment process to occur in Azure DevOps pipeline - fixes Issue #181
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/182)

Refactor PSake File to Perform Deployment in Azure DevOps - Fixes #179

---

CHANGELOG.md
README.md
docs/Get-CosmosDbAccountConnectionString.md
src/CosmosDB.psd1
src/en-US/CosmosDB.strings.psd1
src/lib/accounts.ps1
test/CosmosDB.accounts.Tests.ps1
test/CosmosDB.integration.Tests.ps1

This PR adds the `Get-CosmosDbAccountConnectionString` function. However, this function does not currently return anything due to a bug in the Microsoft/DocumentDB Provider in Azure. See [this issue](https://github.com/Azure/azure-powershell/issues/3650).
The function will display a warning stating that this function does not currently return the connection strings as expected.
I will leave issue #163 open until this is fixed.
- Enhancement #163
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/187)

Added Get-CosmosDbAccountConnectionString Function

---

CHANGELOG.md
README.md
RELEASENOTES.md
docs/CosmosDB.md
docs/New-CosmosDbCollection.md
docs/New-CosmosDbCollectionUniqueKey.md
docs/New-CosmosDbCollectionUniqueKeyPolicy.md
docs/Set-CosmosDbCollection.md
src/CosmosDB.psd1
src/CosmosDB.psm1
src/lib/collections.ps1
test/Integration/CosmosDB.integration.Tests.ps1
test/Unit/CosmosDB.collections.Tests.ps1
test/Unit/CosmosDB.utils.Tests.ps1

This PR adds support for creating and updating Unique Key Policies in Cosmos DB collections.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/204)

Added support for UniqueKeyPolicy in Collections - Fixes #197

---

CHANGELOG.md
src/en-US/CosmosDB.strings.psd1
src/lib/users/Assert-CosmosDbUserIdValid.ps1
src/lib/users/Get-CosmosDbUser.ps1
src/lib/users/Get-CosmosDbUserResourcePath.ps1
src/lib/users/New-CosmosDbUser.ps1
src/lib/users/Remove-CosmosDbUser.ps1
src/lib/users/Set-CosmosDbUser.ps1
test/Unit/CosmosDB.users.Tests.ps1

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/229)

Improved validation on User Defined Function Id parameter on *-CosmosDBUser* functions

---

CHANGELOG.md
RELEASENOTES.md
src/CosmosDB.psd1
src/en-US/CosmosDB.strings.psd1
src/lib/accounts/Assert-CosmosDbAccountNameValid.ps1
test/Unit/CosmosDB.accounts.Tests.ps1

This PR extends the account name character limit to 50 chars, even though the portal reports the limit as 31 chars. This PR fixes #241.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/242)

Extend Account Name limit to 50 characters - Fixes #241

---

CHANGELOG.md
README.md
cosmosdb.depend.psd1
docs/New-CosmosDbCollectionIncludedPathIndex.md
src/CosmosDB.psd1
src/CosmosDB.psm1
src/en-US/CosmosDB.strings.psd1
src/lib/collections/New-CosmosDbCollection.ps1
src/lib/collections/New-CosmosDbCollectionIncludedPathIndex.ps1
test/Integration/CosmosDB.integration.Tests.ps1
test/Unit/CosmosDB.collections.Tests.ps1

Correct Notes display in Markdown README.MD.
Deprecate Hash index policy and precision.
- Fixes #269 
- Fixes #271 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/270)

Fix Notes display in Markdown and Index Policy - Fixes #269

---

CHANGELOG.md
RELEASENOTES.md
cosmosdb.depend.psd1
docs/Get-CosmosDbAttachment.md
docs/New-CosmosDbAttachment.md
docs/Remove-CosmosDbAttachment.md
docs/Set-CosmosDbAttachment.md
src/CosmosDB.psd1
src/lib/attachments/Get-CosmosDbAttachment.ps1
src/lib/attachments/New-CosmosDbAttachment.ps1
src/lib/attachments/Remove-CosmosDbAttachment.ps1
src/lib/attachments/Set-CosmosDbAttachment.ps1
test/Integration/CosmosDB.integration.Tests.ps1
test/Unit/CosmosDB.accounts.Tests.ps1
test/Unit/CosmosDB.attachments.Tests.ps1
test/Unit/CosmosDB.collections.Tests.ps1
test/Unit/CosmosDB.databases.Tests.ps1
test/Unit/CosmosDB.documents.Tests.ps1
test/Unit/CosmosDB.offers.Tests.ps1
test/Unit/CosmosDB.permissions.Tests.ps1
test/Unit/CosmosDB.storedprocedures.Tests.ps1
test/Unit/CosmosDB.triggers.Tests.ps1
test/Unit/CosmosDB.userdefinedfunctions.Tests.ps1
test/Unit/CosmosDB.users.Tests.ps1
test/Unit/CosmosDB.utils.Tests.ps1

This PR adds support for setting PartitionKey in *-CosmosDBAttachment functions. This prevents http 400 errors when working with attachments in collections with partition keys.
- Fixes #274
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/276)

Added support for PartitionKey in *-CosmosDBAttachment functions - Fixes #274

---

CHANGELOG.md
requirements.psd1

This PR updates the requirements.psd1 with the latest Azure modules to fix build problems in build agents.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/286)

Update Required Build Modules

---

.travis.yml
CHANGELOG.md
RELEASENOTES.md
appveyor.yml
azure-pipelines.daily.yml
azure-pipelines.yml
psake.ps1
psakefile.ps1
requirements.psd1
src/CosmosDB.psd1
src/CosmosDB.psm1
src/classes/CosmosDB/CosmosDB.cs
src/classes/CosmosDB/CosmosDB.csproj
src/en-US/CosmosDB.strings.psd1
test/Integration/CosmosDB.integration.Tests.ps1
test/Unit/CosmosDB.accounts.Tests.ps1
test/Unit/CosmosDB.attachments.Tests.ps1
test/Unit/CosmosDB.collections.Tests.ps1
test/Unit/CosmosDB.databases.Tests.ps1
test/Unit/CosmosDB.documents.Tests.ps1
test/Unit/CosmosDB.generic.Tests.ps1
test/Unit/CosmosDB.offers.Tests.ps1
test/Unit/CosmosDB.permissions.Tests.ps1
test/Unit/CosmosDB.storedprocedures.Tests.ps1
test/Unit/CosmosDB.triggers.Tests.ps1
test/Unit/CosmosDB.userdefinedfunctions.Tests.ps1
test/Unit/CosmosDB.users.Tests.ps1
test/Unit/CosmosDB.utils.Tests.ps1

- Moved CosmosDB namespace class definitions into C# project to be built
into a .NET Standard 2.0 DLL that can be loaded instead of a CS file.
This is to work around a problem with Azure Functions 2.0 where
types can not be compiled in the runtime (see [this issue](https://github.com/Azure/azure-functions-powershell-worker/issues/220)) -
fixes [Issue #290](https://github.com/PlagueHO/CosmosDB/issues/290).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/294)

Pre-compile Custom Types to enable Functions 2.0 Support - Fixes #290

---

CHANGELOG.md
docs/Set-CosmosDbDocument.md
src/lib/documents/Set-CosmosDbDocument.ps1
test/Unit/CosmosDB.documents.Tests.ps1

**Enhancement**
Currently there is now way to set If-Match header (or any other header) on Set-CosmosDbDocument command. This PR will allow user to set If-Match header so that update query will fail if someone has modified the document before us. Current ETag is fetched from the document by accessing $document._etag field.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/303)

Added ETag field for concurrency resolution on Set-CosmosDbDocument

---

src/lib/documents/New-CosmosDbDocument.ps1

- Refactor the PartionKey to support non-string keys
I'm unable to use the PlatyPS to generate the correct updated docs files for the New-CosmosDBDocument. Running the command from the CONTRIBUTING.md guide, simply generates markdown files with incorrect content.
@PlagueHO
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/311)

Refactor: PartitionKey to support int PartitionKeys

---

CHANGELOG.md
README.md
source/Public/collections/New-CosmosDbCollection.ps1
source/en-US/CosmosDB.strings.psd1

This PR:
- Add warning to `New-CosmosDbCollection` to show when creating a collection
without a partition key.
- Updated `README.MD` to documentation to reduce focus on collections without
partition keys - fixes [Issue #342](https://github.com/PlagueHO/CosmosDB/issues/342).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/345)

Improve Documentation by reducing focus on Non-Partitioned Collections - Fixes #342

---

CHANGELOG.md
azure-pipelines.yml
build.yaml
tests/Integration/CosmosDB.integration.Tests.ps1
tests/Unit/CosmosDB.generic.Tests.ps1

- Added integration tests for executing document queries - Fixes [Issue #356](https://github.com/PlagueHO/CosmosDB/issues/356).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/358)

Add Integration Tests for Document Query

---

CHANGELOG.md
README.md
azure-pipelines.yml
build.yaml
docs/New-CosmosDbCollection.md
docs/New-CosmosDbCollectionCompositeIndexElement.md
docs/New-CosmosDbCollectionExcludedPath.md
docs/New-CosmosDbCollectionIncludedPath.md
docs/New-CosmosDbCollectionIncludedPathIndex.md
docs/New-CosmosDbCollectionIndexingPolicy.md
docs/New-CosmosDbCollectionUniqueKey.md
docs/New-CosmosDbCollectionUniqueKeyPolicy.md
docs/Set-CosmosDbCollection.md
source/CosmosDB.psd1
source/Public/collections/New-CosmosDbCollection.ps1
source/Public/collections/Set-CosmosDbCollection.ps1
source/build.psd1
source/en-US/CosmosDB.strings.psd1
tests/Integration/CosmosDB.integration.Tests.ps1
tests/Unit/CosmosDB.collections.Tests.ps1

- Added `IndexingPolicyJson` parameter to `New-CosmosDbCollection`
and `Set-CosmosDbCollection` functions to enable setting an index policy
using JSON - Fixes [Issue #360](https://github.com/PlagueHO/CosmosDB/issues/360).
- Fixed build pipeline deployment skip function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/361)

Added IndexingPolicyJson Parameter to create Collection - Fixes #360

---

CHANGELOG.md
README.md
azure-pipelines.yml
source/Private/utils/Get-CosmosDbUri.ps1
source/classes/CosmosDB/CosmosDB.cs
tests/Unit/CosmosDB.utils.Tests.ps1

- Added support for AzureChinaCloud (Mooncake) - Fixes [Issue #365](https://github.com/PlagueHO/CosmosDB/issues/365).
- Fix daily build by preventing deployment stage from running on
anything build not named `*.master` - Fixes [Issue #366](https://github.com/PlagueHO/CosmosDB/issues/366).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/367)

Add Support for AzureChinaCloud - Fixes #365

---

CHANGELOG.md
azure-pipelines.yml

- Changed build jobs `Unit_Test_PSCore6_Ubuntu1604` and
`Integration_Test_PSCore6_Ubuntu1604` to install PowerShell Core 6.2.4
to support version of Az PowerShell modules that are installed - Fixes [Issue #371](https://github.com/PlagueHO/CosmosDB/issues/371).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/372)

Update PSCore6_Ubuntu1604 Build Jobs to use PSCore 6.2.4 - Fixes #371

---

CHANGELOG.md
Resolve-Dependency.ps1
STYLEGUIDELINES.md
build.ps1
docs/CosmosDB.md
docs/Get-CosmosDbDocumentJson.md
source/Private/utils/Invoke-CosmosDbRequest.ps1
source/Public/attachments/Get-CosmosDbAttachment.ps1
source/Public/collections/Get-CosmosDbCollection.ps1
source/Public/documents/Get-CosmosDbDocument.ps1
source/Public/documents/Get-CosmosDbDocumentJson.ps1
source/Public/offers/Get-CosmosDbOffer.ps1
tests/TestHelper/TestHelper.psm1
tests/Unit/CosmosDB.documents.Tests.ps1

- Added `Get-CosmosDbDocumentJson` function - Fixes [Issue #370](https://github.com/PlagueHO/CosmosDB/issues/370).
- Refactored `Get-CosmosDbDocument` to be a wrapper for
new function `Get-CosmosDbDocumentJson`.
- Fixed `Get-CosmosDbDocument` function partition key formatting
when an `Id` parameter is passed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/383)

Added Get-CosmosDbDocumentJson function - Fixes #370

---

CHANGELOG.md
README.md
docs/New-CosmosDbContext.md
source/Public/utils/New-CosmosDbContext.ps1
source/en-US/CosmosDB.strings.psd1
tests/Unit/CosmosDB.utils.Tests.ps1

Added support for specifying a protocol and port in the `URI` parameter
of the `New-CosmosDbContext` function - Fixes [Issue #381](https://github.com/PlagueHO/CosmosDB/issues/381).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/385)

Improve URI Parameter Handling in New-CosmosDbContext Function - Fixes #381

---

CHANGELOG.md
source/prefix.ps1

- Fixed `Cannot bind argument to parameter 'Message' because it is null.` error
message occurring when displaying messages on systems not using `en-US`
UI culture - Fixes [Issue #373](https://github.com/PlagueHO/CosmosDB/issues/373).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/387)

Fixed localization bug - Fixes #373

---

CHANGELOG.md
source/Public/utils/New-CosmosDbContext.ps1
source/classes/CosmosDB/CosmosDB.cs
tests/Unit/CosmosDB.utils.Tests.ps1

This PR fixes the value of the Environment property returned in the Context object by `New-CosmosDbContext`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/416)

Correct New-CosmosDbContext Environment output - Fixes #411

---

CHANGELOG.md
RequiredModules.psd1
build.yaml
docs/Get-CosmosDbDocument.md
docs/New-CosmosDbDocument.md
docs/Set-CosmosDbDocument.md
source/Public/documents/Get-CosmosDbDocument.ps1
source/Public/documents/New-CosmosDbDocument.ps1
source/Public/documents/Set-CosmosDbDocument.ps1
source/en-US/CosmosDB.strings.psd1
tests/Unit/CosmosDB.documents.Tests.ps1

This PR:
- Added `ReturnJson` parameter to `New-CosmosDbDocument`, `Set-CosmosDbDocument`
and `Get-CosmosDbDocument` functions to allow return of documents that can
not be converted to objects due to duplicate key names that only differ in
case - Fixes [Issue #413](https://github.com/PlagueHO/CosmosDB/issues/413).
- Fix CI pipeline release stage by adding Sampler GitHub tasks which
were moved out of the main sampler module into a new module
`Sampler.GitHubTasks` - Fixes [Issue #418](https://github.com/PlagueHO/CosmosDB/issues/418).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/419)

Add ReturnJson parameter to Document cmdlets

---

CHANGELOG.md
tests/Unit/CosmosDB.generic.Tests.ps1

This PR suppresses PSSA checks unless run on PowerShell Core 7.0.3 or above or Windows PowerShell..
- Fixes #431
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/432)

Fix unit failures with PSSA - Fixes #431

---

CHANGELOG.md
README.md
azure-pipelines.yml

This PR deprecates tests on Ubuntu 16.04 and adds tests on Ubuntu 20.04. It also removes PowerShell 6.x. tests. It also adds tests on Windows Server 2022.
- Fixes #436
- Fixes #434
- Fixes #433
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/438)

Update tests to deprecated Ubuntu 16.04 and PS 6.x

---

CHANGELOG.md
source/Private/utils/Invoke-CosmosDbRequest.ps1
source/en-US/CosmosDB.strings.psd1

- Fix exception being thrown when a 429 is returned by CosmosDB, but the
`x-ms-retry-after-ms` header is not returned. This may occur in requests
that follow large (> 1MB) insert or updates - Fixes [Issue #439](https://github.com/PlagueHO/CosmosDB/issues/439).
- Fixes #458
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/460)

Fix exception when x-ms-retry-after-ms header missing from 429 error - Fixes #458

---

docs/Get-CosmosDbDocument.md

Small typo fix `RetrunJson` -> `ReturnJson`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/462)

Fix typo in Get-CosmosDbDocument syntax

---

CHANGELOG.md
docs/New-CosmosDbContext.md
source/Public/utils/New-CosmosDbContext.ps1
tests/Integration/CosmosDB.integration.Tests.ps1
tests/Unit/CosmosDB.utils.Tests.ps1

Fixes #426.
Added `-ConnectionString` parameter to `New-CosmosDbContext`.
The new parameter set:
```powershell
New-CosmosDbContext -ConnectionString <securestring> [-Database <string>] [-KeyType <string>] [-MasterKeyType <string>] [-BackoffPolicy <BackoffPolicy>] [-Environment <Environment>] [-WhatIf] [-Confirm] [<CommonParameters>]
```
Which allows the user to pass in a connection string to set the context. Let me know if I need to tweak this or fix anything else 🙂.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PlagueHO/CosmosDB/466)

Added ConnectionString parameter to New-CosmosDbContext cmdlet

---

CHANGELOG.md
README.md
azure-pipelines.yml

Deprecate Ubunutu 18.04 and add Ubunutu 22.04 to build pipelines. Also deprecates MacOS 10.15 testing and adds MacOS 12 testing.
- Fixes #473 
- Fixes #474
- FIxes #476 
- Fixes #477 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PlagueHO/CosmosDB/475)

Removed Ubuntu 18.04 and added Ubuntu 22.04 to build pipeline

---

CHANGELOG.md
build.yaml
docs/New-CosmosDbCollection.md
docs/New-CosmosDbDatabase.md
source/Public/collections/New-CosmosDbCollection.ps1
source/Public/databases/New-CosmosDbDatabase.ps1
tests/Integration/CosmosDB.integration.Tests.ps1
tests/TestHelper/TestHelper.psm1
tests/Unit/CosmosDB.accounts.Tests.ps1
tests/Unit/CosmosDB.collections.Tests.ps1
tests/Unit/CosmosDB.databases.Tests.ps1

Adjust the minimum autoscale throughput for Cosmos DB from 4000 to 1000 and improve the cleanup process for Cosmos DB resources in integration tests. This addresses issues related to resource management.
- Fixes #493
- Fixes #494
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PlagueHO/CosmosDB/495)

Update autoscale throughput minimum and enhance resource cleanup in tests

---

CHANGELOG.md
README.md
azure-pipelines.yml
source/Private/utils/Get-CosmosDbRequestExceptionString.ps1
source/Private/utils/Get-CosmosDbUri.ps1
source/Private/utils/Invoke-CosmosDbRequest.ps1
tests/Unit/CosmosDB.utils.Tests.ps1

- Update CI pipeline to use matrix testing to reduce code duplication
- Add Get-CosmosDbRequestExceptionString function to generate the string output when exception occurs. This is to prepare for masking authorization keys.
- Correct name of ApplicationObjectId variable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PlagueHO/CosmosDB/499)

Refactor Request Exception to move Exception Generation string to new function

---

CHANGELOG.md
azure-pipelines.yml
build.yaml
source/Private/utils/Invoke-CosmosDbRequest.ps1
source/Private/utils/New-CosmosDbInvalidOperationException.ps1
source/Private/utils/New-CosmosDbResponseException.ps1
source/classes/CosmosDB/CosmosDB.cs
source/en-US/CosmosDB.strings.psd1
tests/Integration/CosmosDB.integration.Tests.ps1
tests/Unit/CosmosDB.utils.Tests.ps1

This PR updates the Invoke-CosmosDbRequest function to throw a custom exception of type CosmosDB.ResponseExeption. This is required because the HttpResponseException contains a Response.requestMessage property, which may contain the authorizationHeader.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PlagueHO/CosmosDB/501)

Update Invoke-CosmosDbReqiest to throw a CosmosDB.ResponseExeption instead of a HttpReponseException

---

CHANGELOG.md
README.md
docs/New-CosmosDbContext.md
source/Public/utils/New-CosmosDbContext.ps1
tests/Unit/CosmosDB.utils.Tests.ps1

Adds support to `New-CosmosDbContext` for setting the `EndpointHostname` parameter when using EntraID or Token authentication.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PlagueHO/CosmosDB/505)

Enhance New-CosmosDbContext to support alternate Azure Cloud endpoints - Fixes #504
