PlagueHO/CosmosDB

- CHANGELOG.md
- src/CosmosDB.psd1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/6)
> Release 1.0.2

- CHANGELOG.md
- RELEASENOTES.md
- docs/New-CosmosDbDatabase.md
- docs/Remove-CosmosDbDatabase.md
- src/CosmosDB.psd1
- src/lib/databases.ps1
- test/CosmosDB.collections.Tests.ps1
- test/CosmosDB.databases.Tests.ps1
- test/CosmosDB.permissions.Tests.ps1
- test/CosmosDB.users.Tests.ps1
- test/CosmosDB.utils.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/10)
> Release 1.0.6

- CHANGELOG.md
- README.md
- RELEASENOTES.md
- docs/Get-CosmosDbTrigger.md
- docs/Get-CosmosDbTriggerResourcePath.md
- docs/New-CosmosDbTrigger.md
- docs/Remove-CosmosDbTrigger.md
- docs/Set-CosmosDbTrigger.md
- src/CosmosDB.psd1
- src/lib/triggers.ps1
- src/lib/utils.ps1
- test/CosmosDB.triggers.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/11)
> Release 1.0.7

- CHANGELOG.md
- README.md
- RELEASENOTES.md
- docs/Get-CosmosDbStoredProcedure.md
- docs/Get-CosmosDbStoredProcedureResourcePath.md
- docs/Invoke-CosmosDbStoredProcedure.md
- docs/New-CosmosDbStoredProcedure.md
- docs/Remove-CosmosDbStoredProcedure.md
- docs/Set-CosmosDbStoredProcedure.md
- docs/Set-CosmosDbTrigger.md
- src/CosmosDB.psd1
- src/lib/storedprocedures.ps1
- src/lib/utils.ps1
- test/CosmosDB.storedprocedures.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/12)
> Release 1.0.8

- CHANGELOG.md
- README.md
- src/CosmosDB.psd1
- src/lib/userdefinedfunctions.ps1
- src/lib/utils.ps1
- test/CosmosDB.userdefinedfunctions.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/17)
> Added User Defined Function support - Fixes #13

- CHANGELOG.md
- README.md
- RELEASENOTES.md
- src/CosmosDB.psd1
- src/lib/userdefinedfunctions.ps1
- src/lib/utils.ps1
- test/CosmosDB.userdefinedfunctions.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/18)
> Release 1.0.9

- CHANGELOG.md
- README.md
- RELEASENOTES.md
- src/CosmosDB.psd1
- src/lib/attachments.ps1
- src/lib/utils.ps1
- test/CosmosDB.attachments.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/27)
> Release 1.0.12

- appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/31)
> Release 2.0.0 (Again)

- CHANGELOG.md
- src/lib/permissions.ps1
- test/CosmosDB.permissions.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/36)
> Added support for specifying token expiry length Get-cosmosDbPermission - Fixes #28

- CHANGELOG.md
- src/lib/permissions.ps1
- src/lib/utils.ps1
- test/CosmosDB.permissions.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/38)
> Release to Master

- CHANGELOG.md
- RELEASENOTES.md
- src/CosmosDB.psd1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/47)
> Releasing 2.0.3

- psakefile.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/66)
> Rerelease 2.0.7

- psakefile.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/69)
> Rereleasing 2.0.7

- psakefile.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/71)
> Fix up build process

- psakefile.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/72)
> Test fix deploy

- CHANGELOG.md
- RELEASENOTES.md
- src/CosmosDB.psd1
- src/lib/utils.ps1
- test/CosmosDB.utils.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/78)
> Release 2.0.8

- CHANGELOG.md
- docs/Get-CosmosDbCollectionSize.md
- src/CosmosDB.psd1
- src/lib/collections.ps1
#79 Added support for Get-CosmosDBCollectionSize
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/80)
> #79 - Added Get-CosmosDBCollectionSize.

- CHANGELOG.md
- RELEASENOTES.md
- docs/Get-CosmosDbCollectionSize.md
- src/CosmosDB.psd1
- src/lib/collections.ps1
- test/CosmosDB.collections.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/81)
> Release 2.0.9

- CHANGELOG.md
- RELEASENOTES.md
- src/CosmosDB.psd1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/90)
> Release to 2.0.10

- CHANGELOG.md
- README.md
- RELEASENOTES.md
- src/CosmosDB.psd1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/92)
> Added PowerShell Core Version Badge - Fixes #91

- CHANGELOG.md
- test/CosmosDB.integration.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/94)
> Prevent integration tests from running if Azure connection environment variables are not set - Fixes #93

- CHANGELOG.md
- RELEASENOTES.md
- src/CosmosDB.psd1
- src/lib/documents.ps1
- test/CosmosDB.integration.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/98)
> Fix Get-CosmosDBDocument Issue - Fixes #97

- CHANGELOG.md
- CODE_OF_CONDUCT.md
- README.md
- RELEASENOTES.md
- src/CosmosDB.psd1
- src/lib/documents.ps1
- test/CosmosDB.integration.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/99)
> Release 2.0.11

- CHANGELOG.md
- README.md
- RELEASENOTES.md
- docs/Set-CosmosDbCollection.md
- src/CosmosDB.psd1
- src/lib/collections.ps1
- src/lib/utils.ps1
- test/CosmosDB.collections.Tests.ps1
- test/CosmosDB.integration.Tests.ps1
- Added `Set-CosmosDbCollection` function for updating a collection - See
[Issue #104](https://github.com/PlagueHO/CosmosDB/issues/104).
- Updated `Invoke-CosmosDbRequest` function to output additional exception
information to the Verbose stream - See [Issue #103](https://github.com/PlagueHO/CosmosDB/issues/103).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/106)
> Added Set-CosmosDbCollection

- CHANGELOG.md
- README.md
- RELEASENOTES.md
- docs/Set-CosmosDbCollection.md
- src/CosmosDB.psd1
- src/lib/collections.ps1
- src/lib/utils.ps1
- test/CosmosDB.collections.Tests.ps1
- test/CosmosDB.integration.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/107)
> Releasing 2.0.13

- .codecovio/CodeCovIo.psm1
- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/109)
> Fix CodeCov.io Coverage upload - Fixes #108

- CHANGELOG.md
- RELEASENOTES.md
- src/CosmosDB.psd1
- src/en-US/CosmosDB.strings.psd1
- src/lib/collections.ps1
- test/CosmosDB.collections.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/113)
> Fix New-CosmosDbCollectionIncludedPathIndex Kind Parameter - Fixes #112

- .codecovio/CodeCovIo.psm1
- CHANGELOG.md
- RELEASENOTES.md
- src/CosmosDB.psd1
- src/en-US/CosmosDB.strings.psd1
- src/lib/collections.ps1
- test/CosmosDB.collections.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/114)
> Releasing 2.0.14

- CHANGELOG.md
- README.md
- RELEASENOTES.md
- docs/Invoke-CosmosDbStoredProcedure.md
- src/CosmosDB.psd1
- src/CosmosDB.psm1
- src/en-US/CosmosDB.strings.psd1
- src/lib/collections.ps1
- src/lib/storedprocedures.ps1
- test/CosmosDB.collections.Tests.ps1
- test/CosmosDB.integration.Tests.ps1
- test/CosmosDB.storedprocedures.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/119)
> Releasing 2.0.15

- CHANGELOG.md
- docs/New-CosmosDbCollectionIndexingPolicy.md
- src/lib/collections.ps1
- test/CosmosDB.integration.Tests.ps1
`@PlagueHO`
- Fixes #120
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/121)
> Issue 120 - Added 'None' as a valid IndexingMode

- CHANGELOG.md
- RELEASENOTES.md
- docs/New-CosmosDbCollectionIndexingPolicy.md
- src/CosmosDB.psd1
- src/en-US/CosmosDB.strings.psd1
- src/lib/collections.ps1
- test/CosmosDB.collections.Tests.ps1
- test/CosmosDB.integration.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/123)
> Releasing 2.0.16

- CHANGELOG.md
- README.md
- RELEASENOTES.md
- docs/Get-CosmosDbOffer.md
- docs/Invoke-CosmosDbRequest.md
- src/CosmosDB.psd1
- src/en-US/CosmosDB.strings.psd1
- src/lib/attachments.ps1
- src/lib/collections.ps1
- src/lib/databases.ps1
- src/lib/documents.ps1
- src/lib/offers.ps1
- src/lib/permissions.ps1
- src/lib/storedprocedures.ps1
- src/lib/triggers.ps1
- src/lib/userdefinedfunctions.ps1
- src/lib/users.ps1
- src/lib/utils.ps1
- test/CosmosDB.attachments.Tests.ps1
- test/CosmosDB.collections.Tests.ps1
- test/CosmosDB.databases.Tests.ps1
- test/CosmosDB.documents.Tests.ps1
- test/CosmosDB.integration.Tests.ps1
- test/CosmosDB.offers.Tests.ps1
- test/CosmosDB.permissions.Tests.ps1
- test/CosmosDB.storedprocedures.Tests.ps1
- test/CosmosDB.triggers.Tests.ps1
- test/CosmosDB.userdefinedfunctions.Tests.ps1
- test/CosmosDB.users.Tests.ps1
- test/CosmosDB.utils.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/126)
> Refactor to Remove Invoke-RestMethod to expose Headers to all functions - Fixes #125

- CHANGELOG.md
- RELEASENOTES.md
- src/CosmosDB.psd1
- src/lib/utils.ps1
- test/CosmosDB.integration.Tests.ps1
- test/CosmosDB.utils.Tests.ps1
- test/TestHelper/TestHelper.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/134)
> Correct ReadOnly Key usage - Fixes #133

- CHANGELOG.md
- RELEASENOTES.md
- src/CosmosDB.psd1
- src/lib/utils.ps1
- test/CosmosDB.integration.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/135)
> Fix Freeze when using ErrorAction SilentlyContinue - Fixes #132

- CHANGELOG.md
- RELEASENOTES.md
- src/CosmosDB.psd1
- src/lib/utils.ps1
- test/CosmosDB.integration.Tests.ps1
- test/CosmosDB.utils.Tests.ps1
- test/TestHelper/TestHelper.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/136)
> Releasing 2.1.2

- CHANGELOG.md
- RELEASENOTES.md
- docs/New-CosmosDbCollection.md
- docs/Set-CosmosDbCollection.md
- src/CosmosDB.psd1
- src/lib/collections.ps1
- test/CosmosDB.collections.Tests.ps1
- test/CosmosDB.integration.Tests.ps1
This PR fixes:
- #139 
- #140
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/142)
> Add DefaultTimeToLive to New-CosmosDBCollection and Set-CosmosDBCollection

- CHANGELOG.md
- RELEASENOTES.md
- docs/New-CosmosDbCollection.md
- docs/Set-CosmosDbCollection.md
- src/CosmosDB.psd1
- src/lib/collections.ps1
- src/lib/storedprocedures.ps1
- src/lib/utils.ps1
- test/CosmosDB.collections.Tests.ps1
- test/CosmosDB.integration.Tests.ps1
- test/CosmosDB.utils.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/143)
> Releasing 2.1.3

- CHANGELOG.md
- RELEASENOTES.md
- docs/Set-CosmosDbCollection.md
- src/CosmosDB.psd1
- src/en-US/CosmosDB.strings.psd1
- src/lib/collections.ps1
- test/CosmosDB.collections.Tests.ps1
- test/CosmosDB.integration.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/145)
> Added RemoveDefaultTimeToLive parameter to Set-CosmosDbCollection - Fixes #144

- CHANGELOG.md
- test/CosmosDB.integration.Tests.ps1
- test/TestHelper/AzureDeploy/AzureDeploy.json
- test/TestHelper/TestHelper.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/172)
> Fix Integration Tests running in AppVeyor

- CHANGELOG.md
- RELEASENOTES.md
- appveyor.yml
- azure-pipelines.yml
- build.ps1
- cosmosdb.depend.psd1
- psakefile.ps1
- src/CosmosDB.psd1
- src/lib/storedprocedures.ps1
- src/lib/utils.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/183)
> Releasing 2.1.8

- .gitignore
- CHANGELOG.md
- azure-pipelines.yml
- psakefile.ps1
- test/Integration/CosmosDB.integration.Tests.ps1
- test/Unit/CosmosDB.accounts.Tests.ps1
- test/Unit/CosmosDB.attachments.Tests.ps1
- test/Unit/CosmosDB.collections.Tests.ps1
- test/Unit/CosmosDB.databases.Tests.ps1
- test/Unit/CosmosDB.documents.Tests.ps1
- test/Unit/CosmosDB.generic.Tests.ps1
- test/Unit/CosmosDB.offers.Tests.ps1
- test/Unit/CosmosDB.permissions.Tests.ps1
- test/Unit/CosmosDB.storedprocedures.Tests.ps1
- test/Unit/CosmosDB.triggers.Tests.ps1
- test/Unit/CosmosDB.userdefinedfunctions.Tests.ps1
- test/Unit/CosmosDB.users.Tests.ps1
- test/Unit/CosmosDB.utils.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/189)
> Split unit and integration test execution in CI process so that integration tests - Fixes #184

- azure-pipelines.yml
- psakefile.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/192)
> Releasing 2.1.9

- azure-pipelines.yml
- psakefile.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/193)
>  Releasing 2.1.9

- CHANGELOG.md
- README.md
- RELEASENOTES.md
- docs/Invoke-CosmosDbRequest.md
- docs/New-CosmosDbDocument.md
- docs/Set-CosmosDbDocument.md
- src/CosmosDB.psd1
- src/lib/documents.ps1
- src/lib/utils.ps1
- test/Integration/CosmosDB.integration.Tests.ps1
- test/Unit/CosmosDB.documents.Tests.ps1
- test/Unit/CosmosDB.utils.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/196)
> Releasing 2.1.10

- CHANGELOG.md
- README.md
- docs/Get-CosmosDbAccountMasterKey.md
- src/CosmosDB.psd1
- src/en-US/CosmosDB.strings.psd1
- src/lib/accounts.ps1
- src/lib/utils.ps1
- test/Integration/CosmosDB.integration.Tests.ps1
- test/TestHelper/TestHelper.psm1
- test/Unit/CosmosDB.accounts.Tests.ps1
- test/Unit/CosmosDB.attachments.Tests.ps1
- test/Unit/CosmosDB.collections.Tests.ps1
- test/Unit/CosmosDB.databases.Tests.ps1
- test/Unit/CosmosDB.documents.Tests.ps1
- test/Unit/CosmosDB.offers.Tests.ps1
- test/Unit/CosmosDB.permissions.Tests.ps1
- test/Unit/CosmosDB.storedprocedures.Tests.ps1
- test/Unit/CosmosDB.triggers.Tests.ps1
- test/Unit/CosmosDB.userdefinedfunctions.Tests.ps1
- test/Unit/CosmosDB.users.Tests.ps1
- test/Unit/CosmosDB.utils.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/200)
> Added Get-CosmosDbAccountMasterKey Function - Fixes #162

- CHANGELOG.md
- README.md
- docs/New-CosmosDbAccountMasterKey.md
- src/CosmosDB.psd1
- src/en-US/CosmosDB.strings.psd1
- src/lib/accounts.ps1
- test/Integration/CosmosDB.integration.Tests.ps1
- test/Unit/CosmosDB.accounts.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/202)
>  Added New-CosmosDbAccountMasterKey function - Fixes #164

- CHANGELOG.md
- README.md
- RELEASENOTES.md
- docs/Get-CosmosDbAccountMasterKey.md
- docs/New-CosmosDbAccountMasterKey.md
- docs/New-CosmosDbContext.md
- src/CosmosDB.psd1
- src/en-US/CosmosDB.strings.psd1
- src/lib/accounts.ps1
- src/lib/utils.ps1
- test/Integration/CosmosDB.integration.Tests.ps1
- test/TestHelper/TestHelper.psm1
- test/Unit/CosmosDB.accounts.Tests.ps1
- test/Unit/CosmosDB.attachments.Tests.ps1
- test/Unit/CosmosDB.collections.Tests.ps1
- test/Unit/CosmosDB.databases.Tests.ps1
- test/Unit/CosmosDB.documents.Tests.ps1
- test/Unit/CosmosDB.offers.Tests.ps1
- test/Unit/CosmosDB.permissions.Tests.ps1
- test/Unit/CosmosDB.storedprocedures.Tests.ps1
- test/Unit/CosmosDB.triggers.Tests.ps1
- test/Unit/CosmosDB.userdefinedfunctions.Tests.ps1
- test/Unit/CosmosDB.users.Tests.ps1
- test/Unit/CosmosDB.utils.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/203)
> Releasing 2.1.11

- CHANGELOG.md
- test/Integration/CosmosDB.integration.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/207)
> Added new integration tests for testing simple index policies

- CHANGELOG.md
- src/en-US/CosmosDB.strings.psd1
- src/lib/accounts/Assert-CosmosDbAccountNameValid.ps1
- src/lib/accounts/Assert-CosmosDbResourceGroupNameValid.ps1
- src/lib/accounts/Get-CosmosDbAccount.ps1
- src/lib/accounts/Get-CosmosDbAccountConnectionString.ps1
- src/lib/accounts/Get-CosmosDbAccountMasterKey.ps1
- src/lib/accounts/New-CosmosDbAccount.ps1
- src/lib/accounts/New-CosmosDbAccountMasterKey.ps1
- src/lib/accounts/Remove-CosmosDbAccount.ps1
- src/lib/accounts/Set-CosmosDbAccount.ps1
- test/Unit/CosmosDB.accounts.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/220)
> Improved validation on Name and ResourceGroupName parameters on *-CosmosDBAccount* functions - Fixes #Issue-211

- CHANGELOG.md
- src/en-US/CosmosDB.strings.psd1
- src/lib/databases/Assert-CosmosDbDatabaseIdValid.ps1
- src/lib/databases/Get-CosmosDbDatabase.ps1
- src/lib/databases/Get-CosmosDbDatabaseResourcePath.ps1
- src/lib/databases/New-CosmosDbDatabase.ps1
- src/lib/databases/Remove-CosmosDbDatabase.ps1
- src/lib/utils/New-CosmosDbContext.ps1
- test/Unit/CosmosDB.databases.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/222)
> Improve Database Id Parameter Validation on *-CosmosDbDatabase functions - Fixes #212

- CHANGELOG.md
- src/en-US/CosmosDB.strings.psd1
- src/lib/collections/Assert-CosmosDbCollectionIdValid.ps1
- src/lib/collections/Get-CosmosDbCollection.ps1
- src/lib/collections/Get-CosmosDbCollectionResourcePath.ps1
- src/lib/collections/Get-CosmosDbCollectionSize.ps1
- src/lib/collections/New-CosmosDbCollection.ps1
- src/lib/collections/Remove-CosmosDbCollection.ps1
- src/lib/collections/Set-CosmosDbCollection.ps1
- test/Unit/CosmosDB.collections.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/223)
> Improved validation on Collection Id parameter on *-CosmosDBCollection* functions - Fixes #213

- CHANGELOG.md
- src/en-US/CosmosDB.strings.psd1
- src/lib/collections/Assert-CosmosDbCollectionIdValid.ps1
- src/lib/databases/Assert-CosmosDbDatabaseIdValid.ps1
- src/lib/storedprocedures/Assert-CosmosDbStoredProcedureIdValid.ps1
- src/lib/storedprocedures/Get-CosmosDbStoredProcedure.ps1
- src/lib/storedprocedures/Get-CosmosDbStoredProcedureResourcePath.ps1
- src/lib/storedprocedures/Invoke-CosmosDbStoredProcedure.ps1
- src/lib/storedprocedures/New-CosmosDbStoredProcedure.ps1
- src/lib/storedprocedures/Remove-CosmosDbStoredProcedure.ps1
- src/lib/storedprocedures/Set-CosmosDbStoredProcedure.ps1
- test/Unit/CosmosDB.databases.Tests.ps1
- test/Unit/CosmosDB.storedprocedures.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/224)
> Improved validation on Stored Procedure Id parameter on  `*-CosmosDBStoredProcedure*` functions - Fixes #214

- CHANGELOG.md
- src/en-US/CosmosDB.strings.psd1
- src/lib/triggers/Assert-CosmosDbTriggerIdValid.ps1
- src/lib/triggers/Get-CosmosDbTrigger.ps1
- src/lib/triggers/Get-CosmosDbTriggerResourcePath.ps1
- src/lib/triggers/New-CosmosDbTrigger.ps1
- src/lib/triggers/Remove-CosmosDbTrigger.ps1
- src/lib/triggers/Set-CosmosDbTrigger.ps1
- test/Unit/CosmosDB.triggers.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/225)
> Improved validation on Trigger Id parameter on *-CosmosDBTrigger* functions - Fixes #215

- CHANGELOG.md
- src/en-US/CosmosDB.strings.psd1
- src/lib/userdefinedfunctions/Assert-CosmosDbUserDefinedFunctionIdValid.ps1
- src/lib/userdefinedfunctions/Get-CosmosDbUserDefinedFunction.ps1
- src/lib/userdefinedfunctions/Get-CosmosDbUserDefinedFunctionResourcePath.ps1
- src/lib/userdefinedfunctions/New-CosmosDbUserDefinedFunction.ps1
- src/lib/userdefinedfunctions/Remove-CosmosDbUserDefinedFunction.ps1
- src/lib/userdefinedfunctions/Set-CosmosDbUserDefinedFunction.ps1
- test/Unit/CosmosDB.userdefinedfunctions.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/226)
> Improved validation on User Defined Function Id parameter on *-CosmosDBUserDefinedFunction* functions - Fixes #216

- CHANGELOG.md
- src/en-US/CosmosDB.strings.psd1
- src/lib/documents/Assert-CosmosDbDocumentIdValid.ps1
- src/lib/documents/Get-CosmosDbDocument.ps1
- src/lib/documents/Get-CosmosDbDocumentResourcePath.ps1
- src/lib/documents/New-CosmosDbDocument.ps1
- src/lib/documents/Remove-CosmosDbDocument.ps1
- src/lib/documents/Set-CosmosDbDocument.ps1
- test/Unit/CosmosDB.documents.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/230)
> Improved validation on Document Id parameter on *-CosmosDBDocument* functions - Fixes #227

- CHANGELOG.md
- src/en-US/CosmosDB.strings.psd1
- src/lib/permissions/Assert-CosmosDbPermissionIdValid.ps1
- src/lib/permissions/Get-CosmosDbPermission.ps1
- src/lib/permissions/Get-CosmosDbPermissionResourcePath.ps1
- src/lib/permissions/New-CosmosDbPermission.ps1
- src/lib/permissions/Remove-CosmosDbPermission.ps1
- test/Unit/CosmosDB.permissions.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/231)
> Improved validation on Permission Id parameter on *-CosmosDBPermission* functions - Fixes #218

- CHANGELOG.md
- src/en-US/CosmosDB.strings.psd1
- src/lib/attachments/Assert-CosmosDbAttachmentIdValid.ps1
- src/lib/attachments/Get-CosmosDbAttachment.ps1
- src/lib/attachments/Get-CosmosDbAttachmentResourcePath.ps1
- src/lib/attachments/New-CosmosDbAttachment.ps1
- src/lib/attachments/Remove-CosmosDbAttachment.ps1
- src/lib/attachments/Set-CosmosDbAttachment.ps1
- test/Unit/CosmosDB.attachments.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/232)
> Improved validation on Attachment Id parameter on *-CosmosDBAttachment* functions - Fixes #228

- CHANGELOG.md
- RELEASENOTES.md
- src/CosmosDB.psd1
- test/Unit/CosmosDB.generic.Tests.ps1
Also prepare for re-release required because of bad manifest
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/238)
> Added tests for validating module manifest - Fixes #236

- CHANGELOG.md
- RELEASENOTES.md
- src/CosmosDB.psd1
- test/Unit/CosmosDB.generic.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/239)
> Re-releasing 2.1.13

- CHANGELOG.md
- RELEASENOTES.md
- src/CosmosDB.psd1
- src/en-US/CosmosDB.strings.psd1
- src/lib/accounts/Assert-CosmosDbAccountNameValid.ps1
- test/Unit/CosmosDB.accounts.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/243)
> Releasing 2.1.14

- CHANGELOG.md
- CODE_OF_CONDUCT.md
- README.md
- RELEASENOTES.md
- cosmosdb.depend.psd1
- psakefile.ps1
- src/CosmosDB.psd1
- src/en-US/CosmosDB.strings.psd1
- src/lib/accounts/New-CosmosDbAccountMasterKey.ps1
- src/lib/utils/New-CosmosDbContext.ps1
- test/Integration/CosmosDB.integration.Tests.ps1
- test/TestHelper/TestHelper.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/256)
> Minor Improvements to Practice Adherence - Fixes #255

- CHANGELOG.md
- docs/New-CosmosDbAccount.md
- docs/Set-CosmosDbAccount.md
- src/lib/accounts/New-CosmosDbAccount.ps1
- src/lib/accounts/Remove-CosmosDbAccount.ps1
- src/lib/accounts/Set-CosmosDbAccount.ps1
- test/Integration/CosmosDB.integration.Tests.ps1
- test/Unit/CosmosDB.accounts.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/261)
> Added support for setting and updating Cross-Origin Resource Sharing - Fixes #249

- CHANGELOG.md
- README.md
- src/CosmosDB.psd1
- src/CosmosDB.psm1
This PR makes minor improvements to the module manifest to ensure dependencies are installed and specifying supported desktop versions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/264)
> Add RequiredModules to Manifest and other Manifest Improvements - Fixes #263

- CHANGELOG.md
- RELEASENOTES.md
- cosmosdb.depend.psd1
- docs/Get-CosmosDbAttachment.md
- docs/New-CosmosDbAttachment.md
- docs/Remove-CosmosDbAttachment.md
- docs/Set-CosmosDbAttachment.md
- src/CosmosDB.psd1
- src/lib/attachments/Get-CosmosDbAttachment.ps1
- src/lib/attachments/New-CosmosDbAttachment.ps1
- src/lib/attachments/Remove-CosmosDbAttachment.ps1
- src/lib/attachments/Set-CosmosDbAttachment.ps1
- test/Integration/CosmosDB.integration.Tests.ps1
- test/Unit/CosmosDB.accounts.Tests.ps1
- test/Unit/CosmosDB.attachments.Tests.ps1
- test/Unit/CosmosDB.collections.Tests.ps1
- test/Unit/CosmosDB.databases.Tests.ps1
- test/Unit/CosmosDB.documents.Tests.ps1
- test/Unit/CosmosDB.offers.Tests.ps1
- test/Unit/CosmosDB.permissions.Tests.ps1
- test/Unit/CosmosDB.storedprocedures.Tests.ps1
- test/Unit/CosmosDB.triggers.Tests.ps1
- test/Unit/CosmosDB.userdefinedfunctions.Tests.ps1
- test/Unit/CosmosDB.users.Tests.ps1
- test/Unit/CosmosDB.utils.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/278)
> Releasing 3.2.1

- CHANGELOG.md
- README.md
- appveyor.yml
- azure-pipelines.daily.yml
- azure-pipelines.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/280)
> Add Azure Pipelines YAML definition for Daily builds - Fixes #272

- CHANGELOG.md
- README.md
- RELEASENOTES.md
- appveyor.yml
- azure-pipelines.daily.yml
- azure-pipelines.yml
- cosmosdb.depend.psd1
- src/CosmosDB.psd1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/281)
> Releasing 3.2.2

- CHANGELOG.md
- requirements.psd1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/289)
> Change equirements.psd1 to specify minimumversion of Az.Resources and Az.Accounts.

- CHANGELOG.md
- docs/Get-CosmosDbAccountConnectionString.md
- docs/Get-CosmosDbAccountMasterKey.md
- src/en-US/CosmosDB.strings.psd1
- src/lib/accounts/Get-CosmosDbAccountConnectionString.ps1
- test/Integration/CosmosDB.integration.Tests.ps1
- test/Unit/CosmosDB.accounts.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/292)
> Remove Warning from Get-CosmosDbAcountConnectionString and Fix - Fixes #291

- CHANGELOG.md
- RELEASENOTES.md
- docs/Get-CosmosDbAccountConnectionString.md
- docs/Get-CosmosDbAccountMasterKey.md
- requirements.psd1
- src/CosmosDB.psd1
- src/en-US/CosmosDB.strings.psd1
- src/lib/accounts/Get-CosmosDbAccountConnectionString.ps1
- test/Integration/CosmosDB.integration.Tests.ps1
- test/Unit/CosmosDB.accounts.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/293)
> Release 3.2.4

- src/CosmosDB.psd1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/297)
> Releasing 3.3.0.0

- CHANGELOG.md
- RELEASENOTES.md
- psakefile.ps1
- src/CosmosDB.psd1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/298)
> Re-releasing 3.3.0.0

- CHANGELOG.md
- README.md
- RELEASENOTES.md
- docs/New-CosmosDbDatabase.md
- src/CosmosDB.psd1
- src/lib/databases/New-CosmosDbDatabase.ps1
- test/Integration/CosmosDB.integration.Tests.ps1
- test/Unit/CosmosDB.databases.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/301)
> Added OfferThroughput parameter to New-CosmosDbDatabase - Fixes #110

- CHANGELOG.md
- README.md
- RELEASENOTES.md
- docs/New-CosmosDbDatabase.md
- src/CosmosDB.psd1
- src/lib/databases/New-CosmosDbDatabase.ps1
- test/Integration/CosmosDB.integration.Tests.ps1
- test/Unit/CosmosDB.databases.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/302)
> Releasing 3.4.0

- .markdownlint.json
- CHANGELOG.md
- README.md
- azure-pipelines.daily.yml
- azure-pipelines.yml
- test/Integration/CosmosDB.integration.Tests.ps1
- test/TestHelper/TestHelper.psm1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/305)
> Fix issue with integration tests in PRs - Fixes #304

- .markdownlint.json
- CHANGELOG.md
- README.md
- RELEASENOTES.md
- azure-pipelines.daily.yml
- azure-pipelines.yml
- docs/Set-CosmosDbDocument.md
- src/CosmosDB.psd1
- src/lib/documents/Set-CosmosDbDocument.ps1
- test/Integration/CosmosDB.integration.Tests.ps1
- test/TestHelper/TestHelper.psm1
- test/Unit/CosmosDB.documents.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/306)
> Releasing 3.5.0.0

- CHANGELOG.md
- src/CosmosDB.psd1
- src/en-US/CosmosDB.strings.psd1
- src/lib/utils/Get-CosmosDbAuthorizationHeadersFromContext.ps1
- src/lib/utils/Invoke-CosmosDbRequest.ps1
- test/Unit/CosmosDB.documents.Tests.ps1
This PR is to refactor Invoke-CosmosDbRequest to reduce size of the function. Added Get-CosmosDbAuthorizationHeadersFromContext function.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/309)
> Refactor Invoke-ComsosDbRequest

- .travis.yml
- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/314)
> Fix TravisCI Build for MacOS by removing Brew Bootstrap - Fixes #313

- src/lib/documents/New-CosmosDbDocument.ps1
Reverts PlagueHO/CosmosDB#311
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/315)
> Revert "Refactor: PartitionKey to support int PartitionKeys"

- .travis.yml
- CHANGELOG.md
- README.md
- RELEASENOTES.md
- docs/Get-CosmosDbDocument.md
- docs/New-CosmosDbDocument.md
- docs/Remove-CosmosDbDocument.md
- docs/Set-CosmosDbDocument.md
- psakefile.ps1
- requirements.psd1
- src/CosmosDB.psd1
- src/en-US/CosmosDB.strings.psd1
- src/lib/documents/Format-CosmosDbDocumentPartitionKey.ps1
- src/lib/documents/Get-CosmosDbDocument.ps1
- src/lib/documents/New-CosmosDbDocument.ps1
- src/lib/documents/Remove-CosmosDbDocument.ps1
- src/lib/documents/Set-CosmosDbDocument.ps1
- src/lib/utils/Get-CosmosDbAuthorizationHeadersFromContext.ps1
- src/lib/utils/Invoke-CosmosDbRequest.ps1
- test/Unit/CosmosDB.documents.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/317)
> Releasing 3.5.1

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/335)
> Updating ChangeLog since release of v3.6.1

- CHANGELOG.md
- README.md
Fix the build badges.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/341)
> Fix build badges - Fixes #340

- CHANGELOG.md
- README.md
- docs/Get-CosmosDbUri.md
- docs/New-CosmosDbContext.md
- source/Private/utils/Get-CosmosDbUri.ps1
- source/Public/utils/New-CosmosDbContext.ps1
- source/classes/CosmosDB/CosmosDB.cs
- tests/Unit/CosmosDB.utils.Tests.ps1
Add support for AzureUSGovernment when generating a context.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/346)
> Add support for AzureUSGovernment - Issue #332

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/347)
> Updating ChangeLog since release of v3.7.0

- CHANGELOG.md
- azure-pipelines.yml
Revert pipeline code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/362)
> Fix Deployment in Azure DevOps

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/364)
> Updating ChangeLog since release of v4.0.0

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/368)
> Updating ChangeLog since release of v4.1.0

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/386)
> Updating ChangeLog since release of v4.2.0

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/388)
> Updating ChangeLog since release of v4.2.1

- CHANGELOG.md
- Deploy.PSDeploy.ps1
- GitVersion.yml
- README.md
- azure-pipelines.yml
This PR converts Master branch to Main.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/394)
> Convert master to main - Fixes #393

- CHANGELOG.md
- tests/Unit/CosmosDB.collections.Tests.ps1
Fix misspelling of Throughput in README.md
Fixes #396
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/397)
> Fix misspelling of Throughput - Fixes #396

- CHANGELOG.md
- README.md
- docs/New-CosmosDbCollection.md
- docs/New-CosmosDbDatabase.md
- source/Public/collections/New-CosmosDbCollection.ps1
- source/Public/databases/Get-CosmosDbDatabase.ps1
- source/Public/databases/Get-CosmosDbDatabaseResourcePath.ps1
- source/Public/databases/New-CosmosDbDatabase.ps1
- source/Public/databases/Remove-CosmosDbDatabase.ps1
- source/en-US/CosmosDB.strings.psd1
- tests/Integration/CosmosDB.integration.Tests.ps1
- tests/Unit/CosmosDB.collections.Tests.ps1
- tests/Unit/CosmosDB.databases.Tests.ps1
Added support for autoscaling throughput on database and collection in
`New-CosmosDbDatabase` and `New-CosmosDbCollection`
- Fixes #321
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/398)
> Add support for Autoscale databases and collections - Fixes #321

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/399)
> Updating ChangeLog since v4.4.0 +semver:skip

- CHANGELOG.md
- GitVersion.yml
- source/Private/utils/Convert-CosmosDbRequestBody.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/402)
> Fix Module Help - Fixes #409

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/403)
> Updating ChangeLog since release of v4.4.1

- CHANGELOG.md
- build.yaml
- source/Private/attachments/Assert-CosmosDbAttachmentIdValid.ps1
- source/Public/attachments/Get-CosmosDbAttachment.ps1
- source/Public/attachments/New-CosmosDbAttachment.ps1
- source/Public/attachments/Remove-CosmosDbAttachment.ps1
- source/Public/attachments/Set-CosmosDbAttachment.ps1
- source/en-US/CosmosDB.strings.psd1
- tests/Integration/CosmosDB.integration.Tests.ps1
This PR should fix the build process to correct documentation output and produce the compiled DLL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/404)
> Fix build process

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/405)
> Updating ChangeLog since release of v4.4.2

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/407)
> Updating ChangeLog since release of v4.4.3

- CHANGELOG.md
- azure-pipelines.yml
Fix CI pipeline deployment stage to ensure detection of Azure DevOps environment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/409)
> Fix CI pipeline deployment stage

- CHANGELOG.md
- RequiredModules.psd1
- source/classes/CosmosDB/CosmosDB.cs
This PR:
- Update `requirements.psd1` to install modules `Az.Accounts`
2.2.8 - Fixes [Issue #415](https://github.com/PlagueHO/CosmosDB/issues/415).
- Updated `ComsosDB.cs` to add getters and setters to properties - Fixes [Issue #417](https://github.com/PlagueHO/CosmosDB/issues/417).
- Fixes #415 
- Fixes #417
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/420)
> Add Getters Setters to classes in CosmosDB.cs - Fixes #417

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/421)
> Updating ChangeLog since release of v4.5.0

- CHANGELOG.md
- azure-pipelines.yml
This PR updates the build task to us the ubuntu-latest agent image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/423)
> Update build task to use ubuntu-latest - Fixes #422

- CHANGELOG.md
- README.md
- azure-pipelines.yml
This PR adds testing on `macos-11` and updates the `macos-10.14` image to `macos-10.15`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/452)
> Update MacOS build images - Fixes #450

- CHANGELOG.md
- RequiredModules.psd1
- azure-pipelines.yml
- build.ps1
This PR updates the CD pipeline to the latest sampler pattern and fixes some issues with the build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/456)
> Fix Continuous Delivery Pipeline and Update to latest Sampler

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/461)
> Updating ChangeLog since release of v4.6.0

- CHANGELOG.md
- docs/Get-CosmosDbAccountMasterKey.md
- docs/New-CosmosDbDocument.md
- docs/Set-CosmosDbDocument.md
This PR corrects more spelling errors in documentation.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/plagueho/cosmosdb/463)
> Fix spelling errors in documentation

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PlagueHO/CosmosDB/467)
> Updating ChangeLog since release of v4.7.0

- CHANGELOG.md
- README.md
I have made some style-based changes to the README and divided the changes into two commits so they can be cherry-picked if desired. Perhaps you want to accept one change but not the other.
- Made README prettier and more aligned with the style guide which requests the use of splats.
It says to contact an administrator -- the only person I know is @PlagueHO so I'll ping him 💀
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PlagueHO/CosmosDB/471)
> Style-based Changes to README

- CHANGELOG.md
- source/prefix.ps1
This PR picks up abandoned PR #414 . It chances the module so that it doesn't import the dependent Az.Resource and Az.Account modules if they aren't already loaded.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PlagueHO/CosmosDB/484)
> Optimize module loading performance

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PlagueHO/CosmosDB/488)
> Updating ChangeLog since release of v5.0.0

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PlagueHO/CosmosDB/496)
> Updating ChangeLog since release of v5.1.0

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PlagueHO/CosmosDB/503)
> Updating ChangeLog since release of v6.0.0

- README.md
- azure-pipelines.yml
Due to running out of credit to run integration tests in MSDN environment, change to MCAPS environment.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PlagueHO/CosmosDB/506)
> Update variable group in Test stage for clarity on AzureSP usage

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PlagueHO/CosmosDB/507)
> Updating ChangeLog since release of v6.0.1

- CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/PlagueHO/CosmosDB/515)
> Updating ChangeLog since release of v6.1.0
